### ISSUE TITLE
Join the recovery threads.

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#284]
## Problem

In the Maker server, we sometimes launch the recovery thread. But we don't join them after completion. They should be joined.

Ex:
https://github.com/citadel-tech/coinswap/blob/bab961479c780ea7ee8402772e83b942e5c443d0/src/maker/api.rs#L478-L483

## Approach.

- Make a globally accessible thread pool in the Maker struct definition.
- Add the recovery thread as well as all other thread in this thread pool.
- Join all the threads from this pool at shutdown.

**Comment by Shourya742** [comment]
Hey @mojoX911, I was thinking about the issue with the unjoined recovery threads in the Maker server. Instead of manually joining them, we could use scoped threads to handle this more cleanly. Using scoped threads would ensure that any threads we spawn would be guaranteed to complete within the scope they're created, and we wouldn’t need to manually track or join them at shutdown. What do you thoughts on this?

**Comment by mojoX911** [comment]
If it works and keeps the behavior intact I am fine with it. 

My only concern is, as the recovery thread takes a very long time to return (144 blocks of waiting), it will surely last longer than the calling function. I don't know if in case of scope threads it will make the calling function blocking on the spawned thread? If it does then it would hang the rest of the app until recovery finishes.

Whereas currently we have an async type behavior, where recovery can keep happening in the background, while all other app APIs remain operational.

**Comment by mojoX911** [comment]
> But there are several instance where we are waiting just after spawning a normal thread

Seems like the entire `start_maker_server` can be scoped? @Shourya742 ?
