### ISSUE TITLE
[IMP] Maker should decide mining feerates

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#313]
Currently, the taker is deciding the feerate in `SwapParam`. Which can create DOS  vector for Maker. |

https://github.com/citadel-tech/coinswap/blob/0835a5a7d56bceba525133a0ace4b16e3aa58cd8/src/taker/api.rs#L76-L88

Instead, Makers should decide their fee rates and tell it to taker while initiating a swap.

**Comment by rishkwal** [comment]
I'll take this up

**Comment by mojoX911** [comment]
For now, disabling the param and hardcoding a fee of 1000 sats is fine. Maker logic can be opened later.

**Comment by rishkwal** [comment]
Temporarily fixed by #340

**Comment by KnowWhoami** [comment]
So right now, we have hardcoded the `fee_rate` and in future -> the maker would consider `fee_rate` as per the market dynamics .
But this could create  problems for taker side because may be taker wants to do coinswap urgently and for that `fee_rate` has to be set high. But it can't do so since maker has all the control over `fee_rates` and thus ultimately the duration time in which swap completes.

**Comment by KnowWhoami** [comment]
IMO, Better solution would be :
- `Taker` must have the right to set the `fee_rate` instead of `maker` -> after all, it's the taker who will pay all these mining fees.
- Right now, we can hardcode the `fee_rate`  and similar to what has been done in #340.
- In future , we will  derive the `fee_rate` as per the market dynamics as mentioned in  https://github.com/citadel-tech/coinswap/issues/199 ->  then we can write some logic enabling the `taker` to set fee_rate higher than this but not lower than the  derived `fee_rate`.

**Comment by mojoX911** [comment]
I think you are right. The premise of this issue is wrong. I missed the "taker is paying the fee", so he cannot DOS himself.

ack on hard coding the fee for now, later we will decide the best way to expose this. It will also require a bit more clarification for end users.

With this I think this issue can be now closed?

**Comment by KnowWhoami** [comment]
Closing it ...
